### ISSUE TITLE
Task list for 0.2.0

### ISSUE THREAD

**Issue by DougLau** [muon-data/muon-rs#5]
- [x] Better documentation
   - [x] High level overview in lib.rs
   - [x] Example code for each public function
   - [x] Contributing section in README
 - [x] Testing
   - [x] Substitute mappings
   - [x] datetime
   - [x] date
   - [x] time
 - [x] Implement new types
   - [x] datetime
   - [x] date
   - [x] time
