### ISSUE TITLE
Task list for 0.3.0

### ISSUE THREAD

**Issue by DougLau** [muon-data/muon-rs#7]
- [ ] Default values
   - [ ] Deserialize with `#[serde(default = "path")]` attributes
   - [ ] Deserialize from schema
   - [ ] Omit values equal to default when serializing
- [ ] Schema
   - [ ] Deserialize separate
   - [ ] Serialize prepended
   - [ ] Serialize separate
   - [ ] Value enum without #[derive(Deserialize)]
   - [ ] Serialize from Value enum
 - [ ] Builder for Serializer -- pretty printing options
